###
POST http://127.0.0.1:8082/users/
Content-Type: application/json

{
    "name": "Adao Jr",
    "email": "adao@email.com",
    "password": "12345"
}

### ver todos os users
GET http://127.0.0.1:8082/users/

### ver um user
GET http://127.0.0.1:8082/users/4


### atualizar user
PUT http://127.0.0.1:8082/users/4
Content-Type: application/json

{
    "name": "Junico",
    "email": "junico@email.com"
}

### adicionar medidas de um user
POST http://127.0.0.1:8082/users/4/measures/
Content-Type: application/json

{
    "height":180,
    "weight":100,
    "neck":50,
    "biceps":50,
    "chest":50,
    "hips":50,
    "waist":50,
    "thighs":50,
    "calf":50
}

### ver medidas de um user
GET http://127.0.0.1:8082/users/4/measures/

### ver a medida de todos os users
GET  http://127.0.0.1:8082/measures/
